apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
    - image: nginx:latest
      name: web-server
      resources: # Define resource limits for the container
        limits:
          memory: "128Mi" # Maximum memory limit for the container
          cpu: "500m" # Maximum CPU limit for the container
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      gitRepo:
        repository: https://github.com/luksa/kubia-website-example.git
        revision: master
        directory: .
