version: '3'
services:
  jenkins:
    container_name: nginx-docker
    build:
      context: .
      dockerfile: Dockerfile  # Tên của Dockerfile của bạn
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:80"
